[workspace]
members = ["consumer", "submitter", "verifier"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
async-nats = "0.33"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
solana-client = "=2.2.7"
solana-sdk = "=2.2.2"
base64 = "0.22"
base64ct = "=1.6.0" 